#!/bin/bash
#PI SETUP SDN TESTLAB

ROOT_UID="0"

#Check if run as root
if [ "$UID" -ne "$ROOT_UID" ] ; then
	echo "Run again as sudo!"
	exit 1
fi

clear

echo "SETUP RPI SDN TESTLAB"

echo "Checking connectivity..."
wget -q --tries=5 --timeout=20 --spider http://google.com
if [[ $? -eq 0 ]]; then
        echo "OK"
else
        echo "NO NETWORK: EXITING"
		exit
fi

echo "Updating packages database..."
apt-get update

echo "Installing required packages..."
apt-get install -y openvswitch-common openvswitch-switch libssl-dev libnl-genl-3-dev

echo "HOSTAPD-CONFIGURATION STARTING..."

echo "Cloning git hostapd ovs patched..."
git clone https://github.com/hschaa/hostapd.git

echo "Making config...."
cd hostapd/hostapd
cp defconfig .config
sed -i '/CONFIG_LIBNL32=y/s/^#//g' .config
make
make install

echo "Creating hostapd config directories under /etc/"
rm -r /etc/hostapd/
mkdir -p /etc/hostapd/
cd ../../

echo "Copying config file under /etc/hostapd/hostapd.conf"
cp hostapd.conf /etc/hostapd/hostapd.conf

echo "OVS-CONFIGURATION STARTING..."

echo "Checking OVS version..."
ovs-vswitchd --version

if [ $? -eq 0 ]; then

   	echo "OK"

else

	echo "FAIL: EXITING"
	exit

fi

echo "Creating ovs bridge br0"
ovs-vsctl add-br br0 &> /dev/null

if [ $? -eq 0 ]; then

   	echo "OK"

else

	echo "FAIL: EXITING"
	exit

fi

echo "Configuring OpenFlow 1.3 as protocol for br0"

ovs-vsctl set bridge br0 protocols=OpenFlow13 &> /dev/null

if [ $? -eq 0 ]; then

   	echo "OK"

else

	echo "FAIL: EXITING"
	exit

fi

echo "Adding eth0 port to bridge br0"

ovs-vsctl add-port br0 eth0  &>> /dev/null

if [ $? -eq 0 ]; then

   	echo "OK"

else

	echo "FAIL: EXITING"
	exit

fi

echo "NET-CONFIGURATION STARTING..."

echo "Setting interfaces config, backup at /etc/network/interfaces.backup"
cp /etc/network/interfaces /etc/network/interfaces.backup
cp interfaces /etc/network/interfaces

echo "Disabling dhcpcd and enabling networking..."
systemctl disable dhcpcd
systemctl enable networking

echo "Modifying kernel routes..."
route add default gw 192.168.1.1 br0
route del default gw 192.168.1.1 eth0

echo "SDN TESTBED installed in $SECONDS"
echo "Rebooting..."
reboot
