#!/bin/bash
#PI SETUP SDN TESTLAB

ROOT_UID="0"

#Check if run as root
if [ "$UID" -ne "$ROOT_UID" ] ; then
	echo "Run again as sudo!"
	exit 1
fi

clear

echo "SETUP RPI SDN TESTLAB"

echo "Checking connectivity..."
wget -q --tries=5 --timeout=20 --spider http://google.com
if [[ $? -eq 0 ]]; then
        echo "OK"
else
        echo "NO NETWORK: EXITING"
		exit
fi

echo "Updating packages database..."
apt-get update

echo "Installing required packages..."
apt-get install -y bridge-utils hostapd

echo "HOSTAPD-CONFIGURATION STARTING..."

echo "Copying config file under /etc/hostapd/hostapd.conf"
cp hostapd.conf /etc/hostapd/hostapd.conf

echo "NET-CONFIGURATION STARTING..."

echo "Setting interfaces config, backup at /etc/network/interfaces.backup"
cp /etc/network/interfaces /etc/network/interfaces.backup
cp interfaces /etc/network/interfaces

echo "Disabling dhcpcd and enabling networking..."
systemctl disable dhcpcd
systemctl networking stop
systemctl networking start
systemctl enable networking

echo "Modifying kernel routes..."
route add default gw 192.168.1.1 br0
route del default gw 192.168.1.1 eth0

echo "IOT TESTLAB installed in $SECONDS"
brctl show
brctl showstp br0
